#!/bin/sh
set -eu

ENV=$1

npm install bbc/cosmos-deploy#v3

node_modules/.bin/cosmos-deploy update-repositories digital-paper-edit-client $ENV 1.0.0
node_modules/.bin/cosmos-deploy update-config digital-paper-edit-client $ENV 1.0.0 || echo "No config files"
node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-client $ENV 1.0.0 dns;
node_modules/.bin/cosmos-deploy provision-stack digital-paper-edit-client $ENV 1.0.0 main

ENV=$ENV make release deploy